=== mihir-parikh/xml_related_technologies/dtd/census/census.dtd
<!ELEMENT census (date, address, person+)>

<!ELEMENT date (year, month, day)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>

<!ELEMENT address (street, city, country, postalcode)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postalcode (#PCDATA)>

<!ELEMENT person (name, age)>
<!ATTLIST person gender (male|female) #REQUIRED>
<!ATTLIST person pid CDATA #REQUIRED>
<!ELEMENT name (first, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== mihir-parikh/xml_related_technologies/dtd/census/census.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE census SYSTEM "census.dtd">
<census>
	<date>
		<year>2003</year>
		<month>10</month>
		<day>11</day>
	</date>
	<address>
		<street>471 Skipstone Lane</street>
		<city>Emerald City</city>
		<country>Oz</country>
		<postalcode>3158</postalcode>
	</address>
	<person gender="male" pid="P270405">
		<name>
			<first>Meeble</first>
			<last>Bigbug</last>
		</name>
		<age>39</age>
	</person>
	<person gender="female" pid="P273882">
		<name>
			<first>Mable</first>
			<last>Bigbug</last>
		</name>
		<age>36</age>
	</person>
	<person gender="male" pid="P472891">
		<name>
			<first>Marble</first>
			<last>Bigbug</last>
		</name>
		<age>11</age>
	</person>
</census>
