=== mihir-parikh/xml_related_technologies/xsd/bookCatalog/bookCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <!-- Garden of Eden design pattern -->
   
   <xs:complexType name="ISBNType">
      <xs:sequence>      
         <xs:element ref="ISBN" minOccurs="0" type="xs:string" />
      </xs:sequence>      
   </xs:complexType>
   <xs:element name="ISBN" type="xs:ISBNType" />   
   
   <xs:attribute name="Series" type="xs:string" />
   <xs:complexType name="TitleType" mixed="true">
      <xs:attribute ref="Series" minOccurs="0" />
   </xs:complexType>
   <xs:element name="Title" type="xs:TitleType" />
   
   <xs:element name="Author" type="xs:string" />
      
   <xs:complexType name="AuthorsType" mixed="true">      
      <xs:element ref="Author" minOccurs="1" maxOccurs="unbounded" />
   </xs:complexType>
   <xs:element name="Authors" type="AuthorsType" />
   
   <xs:element name="Publisher" type="xs:string" />
   <xs:element name="DatePublished" type="xs:string" />
   <xs:element name="Price" type="xs:string" />
   
   <xs:simpleType name="ISBNType">
      <xs:restriction base="xs:string">
         <xs:pattern value="/ISBN-[0-9]{1}-[0-9]{2}-[0-9]{6}-[0-9]{1}/" />
      </xs:restriction>
   </xs:simpleType>
   <xs:attribute type="ISBNType" />
   
   <xs:attribute name="ISBN" type="xs:string" />
   <xs:attribute name="Edition" type="xs:string" />
   <xs:complexType name="BookType" mixed="true">
      <xs:sequence>
	      <xs:element ref="ISBN" minOccurs="0" />
	      <xs:element ref="Title" />
	      <xs:element ref="Authors" />
	      <xs:element ref="Publisher" />
	      <xs:element ref="DatePublished" />
	      <xs:element ref="Price" />
      </xs:sequence>
      <xs:attribute ref="ISBN" />
      <xs:attribute ref="Edition" />
   </xs:complexType>
   <xs:element name="Book" type="BookType" />   
   
   <xs:attribute name="category" type="xs:string" />
   <xs:complexType name="BookCatalogType" mixed="true">
      <xs:element ref="Book" maxOccurs="unbounded" />
      <xs:attribute ref="category" />
   </xs:complexType>    
   <xs:element name="BookCatalog" type="xs:BookCatalogType" />
</xs:schema>

=== mihir-parikh/xml_related_technologies/xsd/bookCatalog/BookCatalog.xml
<?xml version="1.0"?>
<BookCatalog xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" 
			 xsi:noNamespaceSchemaLocation = "bookCatalog.xsd"
			 category="XML Essentials">
	<Book ISBN="ISBN-0-47-141259-7" Edition="Second">		
		<Title>XML Schema Essentials</Title>
		<Authors>
			<Author>R. Allen Wyke</Author>
			<Author>Andrew Watt</Author>
		</Authors>
		<Publisher>John Wiley</Publisher>
		<DatePublished>2002-02</DatePublished>
		<Price>44.99</Price>
	</Book>
	<Book ISBN="ISBN-0-47-120548-6" Edition="Third">
		<Title>XPath Essentials</Title>
		<Authors>
			<Author>Andrew Watt</Author>
		</Authors>
		<Publisher>John Wiley</Publisher>
		<DatePublished>2001-10</DatePublished>
		<Price>49.99</Price>
	</Book>
	<Book ISBN="ISBN-0-67-232479-2" Edition="First">
		<Title Series="XQuery">XQuery Kick Start</Title>
		<Authors>
			<Author>James McGovern</Author>
			<Author>Per Bothner</Author>
			<Author>Kurt Cagle</Author>
			<Author>James Linn</Author>
			<Author>Vaidyanathan Nagarajan</Author>
		</Authors>
		<Publisher>John Wiley</Publisher>
		<DatePublished>2003-09</DatePublished>
		<Price>34.99</Price>
	</Book>
</BookCatalog>
