=== mihir-parikh/xml_related_technologies/xsd/database_inventory/DatabaseInventory.xsd
<?xml version = "1.0" encoding = "utf-8" ?>

<!-- The xml schema is developed using the Garden of Eden design pattern -->
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
	<!-- Attribute Extension has to be maximum 4 chars in length and should start with 6 -->
	<xs:simpleType name="ExtensionRestrictions">
		<xs:restriction base="xs:string">
			<!-- Regular expression for: The value should be 4 chars in length -->
			<xs:pattern value="[0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- As a rule of Garden of Eden design pattern, declaring attirbutes globally -->
	<xs:attribute name="EmailAlias" type="xs:string" />
	<xs:attribute name="Extension" type="ExtensionRestrictions" />
	<xs:complexType mixed="true" name = "adminType">
		<xs:attribute ref="EmailAlias" use="required" />
		<xs:attribute ref="Extension" use="optional" />
	</xs:complexType>
	<xs:element name = "Administrator" type = "adminType" />

	<xs:simpleType name = "commentsType">
		<xs:restriction base="xs:string">
			<!-- Maximum length of Comments is 99 characters -->
			<xs:maxLength value="99" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Comments" type = "commentsType" />

	<!-- Declaring simpleType, so it can be used for OracleSID as well as for DatabaseAttributes -->
	<xs:simpleType name = "reuseEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Production" />
			<xs:enumeration value="Development" />
			<xs:enumeration value="Testing" />
		</xs:restriction>
	</xs:simpleType>

	<!-- The value of OracleSID can be string Production or Development or Testing -->
	<xs:element name="OracleSID" type="reuseEnum" />

	<xs:simpleType name = "VersionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="7" />
			<xs:enumeration value="8" />
			<xs:enumeration value="8i" />
			<xs:enumeration value="9i" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Reusing type -->
	<xs:attribute name="Type" type="reuseEnum"  />
	<xs:attribute name="Version"  default="9i" type = "VersionType" />
	<xs:complexType name = "DatabaseAttributesType">
		<xs:attribute ref="Type" use="required" />
		<xs:attribute ref="Version" use="optional" />
	</xs:complexType>
	<xs:element name="DatabaseAttributes" type = "DatabaseAttributesType" />

	<!-- <xs:complexType mixed="true" name = "GlobalDatabaseNameDomainType" /> -->
	<xs:element name="GlobalDatabaseName" type = "xs:string" />

	<xs:element name="DatabaseDomain" type = "xs:string" />

	<xs:complexType name = "DatabaseNameType">
		<xs:sequence>
			<xs:element ref="GlobalDatabaseName" />
			<xs:element ref="OracleSID" />
			<xs:element ref="DatabaseDomain" />
			<xs:element ref="Administrator" maxOccurs="3" />
			<xs:element ref="DatabaseAttributes" />
			<xs:element ref="Comments" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DatabaseName" type = "DatabaseNameType" />

	<xs:complexType name = "DatabaseInventoryType">
		<xs:sequence>
			<!-- Occurunces: 1 to many -->
			<xs:element ref="DatabaseName" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DatabaseInventory" type = "DatabaseInventoryType" />

</xs:schema>

=== mihir-parikh/xml_related_technologies/xsd/database_inventory/DatabaseInventory.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Linking xml with xsd -->
<DatabaseInventory xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation = "DatabaseInventory.xsd">

  <DatabaseName>
    <GlobalDatabaseName>production.iDevelopment.info</GlobalDatabaseName>
    <OracleSID>Production</OracleSID>
    <DatabaseDomain>iDevelopment.info</DatabaseDomain>
    <Administrator EmailAlias="jhunter" Extension="6007">Jeffrey Hunter</Administrator>
    <DatabaseAttributes Type="Production" Version="9i"/>
    <Comments>
      The following database should be considered the most stable for
      up-to-date data.
    </Comments>
  </DatabaseName>

  <DatabaseName>
    <GlobalDatabaseName>development.iDevelopment.info</GlobalDatabaseName>
    <OracleSID>Development</OracleSID>
    <DatabaseDomain>iDevelopment.info</DatabaseDomain>
    <Administrator EmailAlias="jhunter" Extension="6007">Jeffrey Hunter</Administrator>
    <Administrator EmailAlias="mhunter" Extension="6008">Melody Hunter</Administrator>
    <DatabaseAttributes Type="Development" Version="9i"/>
    <Comments>
      The following database should contain all hosted applications.
    </Comments>
  </DatabaseName>

  <DatabaseName>
    <GlobalDatabaseName>testing.iDevelopment.info</GlobalDatabaseName>
    <OracleSID>Testing</OracleSID>
    <DatabaseDomain>iDevelopment.info</DatabaseDomain>
    <Administrator EmailAlias="jhunter" Extension="6007">Jeffrey Hunter</Administrator>
    <Administrator EmailAlias="mhunter" Extension="6008">Melody Hunter</Administrator>
    <Administrator EmailAlias="ahunter">Alex Hunter</Administrator>
    <DatabaseAttributes Type="Testing" Version="9i"/>
    <Comments>The following database will host more than half of the testing for our hosting environment.</Comments>
  </DatabaseName>

</DatabaseInventory>
