=== mihir-parikh/xml_related_technologies/dtd/address-book/address-book.dtd
<!ELEMENT address-book (entry+)>
<!ELEMENT entry (name,address*,tel*,fax*,email*)>
<!ELEMENT name (#PCDATA|fname|lname)*>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT address (street,region?,locality,postal-code,country)>
<!ATTLIST address preferred (true|false) "false">
<!ELEMENT street (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT postal-code (#PCDATA)>
<!ELEMENT locality (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ATTLIST tel preferred (true|false) "false">
<!ELEMENT fax (#PCDATA)>
<!ATTLIST fax preferred (true|false) "false">
<!ELEMENT email EMPTY>
<!ATTLIST email href CDATA #REQUIRED
preferred (true|false) "false">

=== mihir-parikh/xml_related_technologies/dtd/address-book/address-book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE address-book SYSTEM "address-book.dtd">
<address-book>
   <entry>
      <name>John Doe</name>
      <address preferred="false">
         <street>34 Fountain Square Plaza</street>
         <region>Cincinnati</region>
         <locality>OH</locality>
         <postal-code>46782</postal-code>
         <country>USA</country>
      </address>
      <tel preferred="true">513-565-7878</tel>
      <fax preferred="false">513-56-6789</fax>
      <email href="jdoe@email.com" preferred="false" />
   </entry>
   <entry>
      <name>Jack Smith</name>
      <tel preferred="false">513-565-4567</tel>      
      <email href="jsmith@email.com" preferred="false" />
   </entry>
</address-book>
